#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    miso_tester.sh                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lde-san- <lde-san-@student.42porto.co      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/23 20:04:01 by lde-san-          #+#    #+#              #
#    Updated: 2026/03/23 20:04:01 by lde-san-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#!/bin/bash

NEOR='\001\033[3m\033[38;2;255;153;51m\002'
MINT='\001\033[1;38;2;55;250;133m\002'
ORNG='\001\033[1;38;2;255;153;51m\002'
PURP='\001\033[1;38;2;174;5;252m\002'
PINK='\001\033[1;38;2;255;0;251m\002'
BABY='\001\033[1;38;2;0;255;247m\002'
BLOD='\001\033[1;38;2;255;0;0m\002'
LIME='\001\033[1;38;2;0;255;0m\002'
RSET='\001\033[0m\002'


SHELL_TYPE=$1
TEMP_FILE="${SHELL_TYPE#-}_out.txt"
START_INDEX=${2:-0}

cleanup() {
    rm -f "$TEMP_FILE"
    echo -e "\n\t${PINK}>> ${ORNG}Exited ${BABY}Super-Cool-${MINT}Miso${BABY}-Powered ${ORNG}Tester${PINK} <<${RSET}\n"
    exit 0
}

trap cleanup SIGINT

if [[ "$SHELL_TYPE" != "-miso" && "$SHELL_TYPE" != "-bash" ]]; then
    echo -e "${MINT}Usage: ${BABY}./miso_tester.sh ${ORNG}[${LIME}-miso ${PURP}| ${LIME}-bash${ORNG}] [${LIME}start_index${ORNG}]${RSET}"
    exit 1
fi

# --- Valgrind Prompt
echo -e "${MINT}Run with Valgrind? ${ORNG}(${LIME}y${ORNG}/${BLOD}n${ORNG})${RSET}"
read -p ": " val
if [[ "$val" == "y" ]]; then
    PREFIX="valgrind --leak-check=full --show-leak-kinds=all --suppressions=obj/.valgrind_suppressions.txt"
else
    PREFIX=""
fi

if [[ "$SHELL_TYPE" == "-miso" ]]; then
	SHLL="./minishell"
else
	SHLL="/usr/bin/bash -i"
fi

# --->> TESTS HERE! <<---
TESTS=(
    "ls -la"
    "\"\""
    "echo \\\$?"
    "cd .."
    "cd"
    "cd ."
    "cd."
    "cd -\\necho \$OLDPWD"
    "unset OLDPWD\\ncd -"
    "cd ~"
    "unset HOME\\ncd ~"
    "unset HOME\\ncd"
    "cd src a"
    "cd ../../../.. \\n pwd"
    "cd /usr/bin"
    "cd  ls"
    "cd nonexistent"
    "cd \"\""
    "ls \$jhrgsdhgbd"
    "ls \$lala/bin | head -n 10"
    "export a=-l\\nls \$a"
    "unset PATH\\nls"
    "/dev/urandom"
    "\$LACBOLLA"
    "\\n"
    "unset PATH\\n/usr/bin/whoami\\necho \$PATH"
    "/bin/cat\\nhehehee\\n"
    "/bin/ls -l"
    "/bin/ls lacresta"
    "\$PWD"
    "cat /bin/ls | head -n 20\\n\\n"
    "/bin/ls | wc"
    "ping -c 2 8.8.8.8"
"    ""                           
      
      
"""
    "ls >| out\\nrm out\\necho \"Forced redirection is not a requirement for this subject\""
    "ls >|"
    "./src"
    "echo"
    "echo -n"
    "echo -nnnnn"
    "echo -nnnnnnnnnnnnnnnnnnnnn -n -n oi"
    "echo -nnnnnnnnnnnnnnnnnnnnn -nz -n oi"
    "echo -nz oi"
    "echo This is a test"
    "echo -n This is a test"
    "echo -nnnn This is a test"
    "echo This is a test -nnnn"
    "echo \$?"
    "echo \$"
    "echo ~"
    "echo \$USER"
    "echo \"\$\"USER"
    "echo \$/,,"
    "echo \"'\$''\$'\""
    "echo hi \$'' \$\"\""
    "echo \$USER'\$USER'"
    "echo '\$USER'\"\$USER\""
    "echo '\$USER'"
    "echo \"'\$USER'\""
    "echo '\"\$USER\"'"
    "echo \"\$U\"S\"ER\""
    "echo '\$HOME e \$CASA e \$USER'"
    "echo ''\$HOME e \$CASA e \$USER''"
    "echo ''\$HOME e '\$CASA' e \$USER''"
    "echo \"\$HOME | echo '\$USER'\""
    "echo hello > \"FILENAME WITH SPACE\"\\ncat \"FILENAME WITH SPACE\"\\nrm \"FILENAME WITH SPACE\""
    "echo \"cat lol.c | cat > lol.c\""
    "\"ec\"h\"o\"    bla \" blaaaaaaaaaaaa\""
    "ec'h'o 'asdas'"
    "echo \"Hello World\""
    "echo \"'Hello World'\""
    "\"echo Hello World\""
    "echo Hello World'"
    "\"e\"'c'''h\"o\" Hello"
    "echo \"md\" | wc"
    "echo \"\"carro' | echo 'cama\"\""
    "echo \"fred' | echo 'cama\""
    "echo 42' '42"
    "echo a'b'c'd'e'f'g'h'i'j'k'l'm'n'o'p'q'r's't'"
    "echo a'b'c'd'e'f'g'h'i'j'k'l'm'n'o'p'q'r's't'\\n"
    "echo -n \"42' '42\"\"\""
    "env"
    "env PATH"
    "echo exit | ${SHLL}"
    "echo exit 300 | ${SHLL}"
    "echo exit -300 | ${SHLL}"
    "echo exit +300 | ${SHLL}"
    "echo exit 2 3 | ${SHLL}"
    "echo exit abc | ${SHLL}"
    "echo exit 99999999999999999999999 | ${SHLL}"
    "cat nonexistant"
    "enter ./minishell"
    ">not_executable_file\\nls -la|grep not_executable_file\\ncat not_executable_file\\n./not_executable_file\\necho \$?\\nrm not_executable_file"
    "| echo 1"
    "ls not_existing_file"
    "/bin/ls"
    "/bin/ls teste"
    "bla"
    "./Makefile"
    "\" \""
    "ls > zzz\$USER.txt\\ncat zzz\$USER.txt\\nrm zzz\$USER.txt"
    "ls > zzz\"\$USER\"zzz.txt\\ncat zzz\"\$USER\"zzz.txt\\nrm zzz\"\$USER\"zzz.txt"
    "ls >> z\"zz\$USER\"zzz.txt\\ncat z\"zz\$USER\"zzz.txt\\n rm z\"zz\$USER\"zzz.txt"
    "ls >> z'zz\$USER'zzz.txt\\ncat z'zz\$USER'zzz.txt\\nrm z'zz\$USER'zzz.txt"
    "export"
    "export ="
    "export _\\nexport"
    "export _a\\nexport |grep _a"
    "export_"
    "export n_value\\nexport |grep n_value"
    "export TEST=kaija 12 TEST2=papaija\\nexport | grep TEST"
    "export = a=2 b='4' c=\"10\"\\n echo \$a \$b \$c"
    "export test=\"   abc\" \\nexport | grep test"
    "export test=\"ls -l\"\\n\$test"
    "export test=\"o hello\"\\nech\$test"
    "export test=\"| wc \"\\nls \$test"
    "export test=\"a  bc        def\"\\nexport | grep test"
    "export test\\nexport test=hello\\nexport | grep test"
    "export test=\"a        b         c\"\\n\\nexport | grep test"
    "export ZZ\"Y=aaa\"bb\\nexport | grep ZZY"
    "export WWW=\"     -aaa |  \"\\nexport | grep WWW"
    "export ABC=\$USER\\nexport | grep ABC"
    "export te\$st=lala\\nexport | grep te"
    "export \$lalal=hahhaa"
    "export user=pre\$\"U\"S\"E\"R\\necho \$?\\nexport | grep user"
    "export user=dq\"\$USER\"\\necho \$?\\nexport | grep user"
    "export user=mq\$\"U\"S\"E\"R\\necho \$?\\nexport | grep user"
    "export us\$er=blabla\\necho \$?\\nexport | grep us"
    "export | grep nonexistentvariable\\nunset nonexistentvariable\\necho \$?\\nexport | grep nonexistentvariable"
    "export | grep HOME\\nunset HOME\\nenv | grep HOME"
    "unset"
    "unset weird@%chars"
    "export | grep HOME\\nunset -n HOME\\necho \$?\\nenv | grep HOME\\n\\necho \"-n flag is not required by the subject\"\\n"
    "export | grep SHLVL\\nunset SHL\"VL\"\\nexport | grep SHLVL"
    "<<"
    ">>"
    "cat << end | wc -l\\none\\ntwo\\nthree\\nfour\\nend\\n"
    "cat << end | grep e\\njamon\\nempanada\\nmalvavisco\\nde\\npomarosa\\narroz\\nchocolate\\nend"
    "<< end \\nThis\\nis\\na\\ntest\\nend"
    "<< end | grep e\\nThis\\nis\\na\\ntest\\nend"
    "<< EOF cat\\n\$USER\\n\$HOME\\ncamion\\nEOF\\n"
    "<< \"EOF\" cat\\n\$USER\\n\$HOME\\ncamion\\nEOF\\n"
    "<< 'EOF' cat\\n\$USER\\n\$HOME\\ncamion\\nEOF\\n"
    "<< \"eo\"f cat\\n\$USER\\n\$HOME\\ncamion\\neof"
    "<< \"\$USER\" cat\\n\$HOME\\ncamion\\nEOF\\n\$USER\\n"
    "<< '\$USER' cat\\n\$HOME\\ncamion\\nEOF\\n\$USER\\n"
    "echo \$USER e \$CASA e \"\$ HOME\" e '\$ HOME' \"\$HOME\" '\$HOME' \$HOME\\n\\necho \$USER e \$CASA e \"\$ HOME\" e '\$ HOME' \"\$HOME\" '\$HOME' \$HOME | wc -m"
    "echo \$CASA \$ CAMA\\n\\necho \$CASA \$ CAMA | wc -m"
    "\"ls\" | 'wc'"
    "unset USER | env | grep USER"
    "unset OLDPWD | ls\\n export | grep OLDPWD"
    "echo USER | export USER=bubu\\nexport | grep USER"
    "echo Hello World | | grep e"
    "cat | cat | ls"
    "cat /dev/urandom | head -c 100\\n\\n"
    "| ls"
    "|"
    "ls ||\\n\\n echo \"OR Operand || not required by the subject\""
    "ls || wc\\n\\n echo \"OR Operand || not required by the subject\""
    "ls | | wc"
    "pwd"
    "pwd args"
    "PWD args"
    "echo \"<< \\\"EOF\\' cat\" | ${SHLL}\\n"
    "\"\" | ls"
    "\"\"\"\""
    "echo 'echo \" | ' | ${SHLL}"
    "\"/bin/ls\""
    "export | grep SHLVL\\necho \"export | grep SHLVL\" | ${SHLL}\\nexport | grep SHLVL"
    "\"\"ls\"\""
    "\"'\"ls\"'\""
    "\"\"ls -l\"\""
    "\"pw\"\"\"d"
    "\"ls' | 'wc\""
    "echo \"ls\" \"|\" \"'wc\" | ${SHLL}"
    "ls | grep \"'md | wc -l\\n\\n\"\\n"
    "ls | grep \"'\"md | wc -l"
    "ls | grep \"md\" | wc -l"
    "echo \"cama'\\n\\n\"\\n"
    "echo \"\$HOME | echo '\$USER'\\n\\n\"\\n"
    "echo hello > outfile\\ncat outfile\\nls -l | grep outfile\\nrm outfile"
    "ls \">\" ola\\nls -l | grep ola\\nrm ola"
    "< inacessible_file | cat -e > output\\ncat output\\nls -l | grep output\\nrm output"
    "<"
    ">"
    "< bla"
    "> test\\ncat test\\nls -l | grep test\\nrm test"
    "echo > existingfile\\n< existingfile\\nls -l | grep existingfile\\nrm existingfile"
    "echo hi > testfile\\n < testfile > testfile2\\ncat testfile2\\nls -l | grep testfile \\nrm testfile testfile2"
    "< nonexisting_file"
    "ls >out>>out2>out3\\ncat out3\\nls | grep out\\nrm out out2 out3"
    "ls | grep > out md | wc -l\\ncat out\\nls -l | grep out\\nrm out"
    "echo \"\">out\\ncat < out >> out\\ncat out\\nls -l | grep out\\nrm out"
    "echo pana mio > in\\necho qlq > out\\ncat < in >> out\\ncat out\\nls -l | grep out\\nrm in out"
    "cat < new_file >> new_file"
    "<out3 grep i >grep | <grep wc"
    "echo \"\">grep\\n<out3 grep i >grep | <grep wc\\nrm grep"
    "export fdgsdfhb=\\nexport | grep fdgsd"
    "cat<<-eof\\nhe\\nhe\\n-eof\\neof\\nEOF"
    "cat <<HERE <<DOC\\ntu si\\nsabe\\nHERE\\npapito\\nDOC"
    "<< echo oi\\nhi\\namigo\\nqueso\\necho\\n"
    "<<here oi <<doc\\n hehe\\nwenas\\nhere\\nq loco wn\\ndoc\\n"
    "export GHOST=123 | env | grep GHOST"
    "cat inc/miso.h | grep \");\""
    "cat <inc/miso.h <<HERE <missing <<DOC | echo oi\\nhehe\\nlol\\nHERE\\njsjsjs ok\\nbueno\\nDOC\\n"
    "pre \"\$null\"no"
    "mkdir test\\ncd test\\nmkdir test2\\ncd test2\\nrm -rf ../../test\\ncd"
    "mkdir test\\ncd test\\nmkdir test2\\ncd test2\\nrm -rf ../../test\\ncd .."
    "mkdir test\\ncd test\\nmkdir test2\\ncd test2\\nrm -rf ../../test\\ncd -"
    "mkdir test\\ncd test\\nmkdir test2\\ncd test2\\nrm -rf ../../test\\ncd ../../"
    "mkdir test\\ncd test\\nmkdir test2\\ncd test2\\nrm -rf ../../test\\ncd ../../../.."
    "unset PWD\\npwd"
    "unset PWD\\necho \$PWD\\nmkdir test\\ncd test\\nexport | grep PWD\\ncd -\\n cd .. \\n rm -rf test"
    "export a=g\\necho \$a\\nunset a\\necho \$a"
    ">e\"of\" >ol\"a\"\\nls -l | grep -e eof -e ola\\nrm eof ola"
    "in HD - \$no ; ola"
    "<< \$USER cat\\n'\$USER'\\nEOF\\n\$USER"
    "echo \$PATH"
    "echo hi |  \"|\""
    "echo hello\"\"world"
    "echo -n \"12\"\"34\""
    "echo \"\$PWD\""
    "echo Hello World"
    "echo env | env -i ${SHLL}"
    ">\$USER0"
    "\$EMPTY echo hi"
    "\$EMPTY"
    "echo \"exit_code ->\$? user ->\$USER home -> \$HOME\""
    "echo \$?HELLO"
    "echo gu>invalid\\nchmod 000 invalid\\ncat >one <no >invalid\\nchmod 777 invalid\\nls -l | grep -e invalid -e one\\nrm invalid one"
    "echo gu>invalid\\nchmod 000 invalid\\nls >no >>invalid >>two\\nchmod 777 invalid\\nls -l | grep -e invalid -e no -e two\\n rm invalid no two"
    "echo gu>invalid\\nchmod 000 invalid\\nls >one >invalid\\nchmod 777 invalid\\nls -l | grep -e invalid -e one\\nrm invalid one"
    "cat >file <no \\nls -l|grep file\\nrm file"
    "export a=\"ola adeus\" \\n>\$a\\ncat \"ola adeus\"\\nls -l | grep \"ola adeus\"\\nrm \"ola adeus\""
    "echo gu>invalid\\nchmod 000 invalid\\ncat <Makefile >invalid\\nchmod 777 invalid\\nls -la | grep invalid\\nrm invalid"
    "cat \"\""
    ">existing_file\\ncat existing_file grep \"\"\\nrm existing_file"
    ">papa echo hello >baby\\ncat papa\\ncat baby\\nls -la | grep -e papa -e baby \\nrm papa baby"
    "<<\"\"\\n\\n"
    "<\"\"\\necho \$?\\n>\"\"\\necho \$?\\n >>\"\" \\n\\n"
    " cat ./README.md"
    "test_files/"
    "/test_files"
    "unset PATH\\necho \"ls\"| ${SHLL}"
    "export fdgsdfhb=\\nexport | grep fdgs"
    "<< end\\nThis\\nis\\na heredoc\\ncan u believeit?\\nstrend\\nend\\n"
    " | ls"
    ">existingfile\\n< existingfile\\nrm existingfile"
    "\"ls\" | \"wc\""
    "echo \"export | grep SHLVL\"| ${SHLL}\\nexport | grep SHLVL"
    "export us\$er=blabla\\nexport | grep us"
    "echo \"'\$\"\"\$'\""
    "cat < out >> out\\nls -l|grep out\\n rm out"
    "< not_existing_file"
    "ls\"'\""
    "< nonexisting_file | echo hello > nonexisting_file\\necho \$?\\ncat nonexisting_file\\nrm nonexisting_file"
    "ls' | 'wc"
    "ls\"\""
    "echo hi>existing_file\\necho sth>>existing_file hehe hehe\\necho>>existing_file burubururburu\\n< existing_file | grep h\\n echo \$?\\nrm existing_file  "
    "\" \"  < \" \">\"\""
    "\" \"  < \" \">\" \""
    "cat  < \" \">\" \""
    "cat  < README.md>\" \"\\n cat \" \"\\nrm \" \""
    "echo hi > \"\""
    "echo hi > \" \"\\ncat \" \"\\nrm \" \""
    "echo \"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"\$USER\"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"\\necho \"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"\$USER\"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"| wc -m"
    "echo '\"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"'\$USER''\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"'\\necho '\"'\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"'\$USER''\"'\"'\"'\"''''\"\"\"\"\"'\"'\"\"'\"'\"\"'\"'\"\"'\"''\"'''\"'''\"'\"\"\"\"\"'''''''''''\"\"\"\"\"\"''\"''\"\"'''\"\"\"\"\"\"' | wc -m"
    "pw\"\"d"
    "export user=\"\$USER\"_is_beautiful\\necho \$?\\nexport | grep user "
    "ls \"\"-l\"\""
    "echo >in como estas?\\necho >out qlq papito \" \"\\ncat < in >> out\\necho \$?\\ncat out\\nrm in out"
    "/bin/ls test"
    "echo hi>existing_file\\necho sth>>existing_file hehe hehe\\necho>>existing_file burubururburu\\n < existing_file grep h\\necho \$?\\n cat existing_file\\nrm existing_file"
    "echo hi>existing_file\\necho sth>>existing_file hehe hehe\\necho>>existing_file burubururburu\\n >file <existing_file grep sth\\necho \$?\\ncat file\\nrm file existing_file "
    "cd \$PWD"
    "echo hi amigo> infile\\necho >>infile como estas\\ngrep hi \"<infile\"\\necho \$?\\ncat infile\\nrm infile"
    "echo hi amigo> infile\\necho >>infile como estas\\ngrep hi <infile\\necho \$?\\ncat infile\\nrm infile"
    "doesntexist\\n\\n\\n\\n\\n\\n\\n\\n\\necho \$?"
    "export HELLO=123\\nexport | grep HELLO\\nexport HELLO=\"beautiful world\"\\nexport | grep HELLO"
    "cat <./inc/miso.h|ls"
    "echo gu>invalid_permission\\nchmod 000 invalid_permission\\necho hi | >outfile01 echo bye >invalid_permission\\nchmod 777 invalid_permission\\nrm invalid_permission outfile01"
    "echo \$PWD\\npwd\\nmkdir testesito\\ncd testesito\\necho \$PWD\\npwd\\ncd ..\\nrm -rf testesito"
    "echo hi \$\"''\""
    "env | sort | grep -v SHLVL | grep -v ^_"
    "export VAR=\"a\\\\\\\\\\\\\"b\\\\\\\\\\\\\\\\c\"\\necho \$VAR"
    "\"\$null\""
    "pre\"\$null\"no"
    "\"\$null\"no"
    ">pre\$\"USER\"\\nls -l | grep USER\\nrm preUSER"
    "export a=echo\\n\$a hello"
    "export amiotrofico=\\n export | grep amiotrofico"
    "cmd | echo hi"
    "echo a='\$a'"
    "commandnotfound1 | echo hello"
    "\$\"\""
    "echo LLMIN\\n echo \"exit -9223372036854775808\"| ${SHLL}"
    "echo LLMAX\\n echo \"exit 9223372036854775807\"| ${SHLL}"
    "echo LLMIN - 1\\n echo \"exit -9223372036854775809\"| ${SHLL}"
    "echo LLMAX + 1\\n echo \"exit 9223372036854775808\"| ${SHLL}"
)

if [[ "$SHLL" == "./minishell" && ! -f "./minishell" ]]; then
    echo -e "${BLOD}Error${PINK}: ${NEOR}./minishell not found. Did you ${ORNG}'${MINT}make${ORNG}'${NEOR}?${RSET}"
    exit 1
fi

for (( i=$START_INDEX; i<${#TESTS[@]}; i++ )); do
    clear
    printf "\t\t${PURP} 🦝 ##>--${PINK}>${BABY}> ${MINT}TEST ${LIME}%02d ${BABY}<${PINK}<${PURP}--<## 🦝${RSET}\n\n" "$i"

    if [[ "$SHELL_TYPE" == "-miso" ]]; then
        # Running your misoverse
        echo -e "${TESTS[$i]}\necho \$?" | $PREFIX $SHLL > "$TEMP_FILE" 2>&1
    else
        # Running Bash
        echo -e "${TESTS[$i]}\necho \$?" | $PREFIX $SHLL > "$TEMP_FILE" 2>&1
    fi
    cat "$TEMP_FILE"

    echo -e "\n\t\t🦝${MINT}----------------------------${RSET}🦝"
    echo -e "\n\t\t  ${NEOR}Press ${ORNG}[${BABY}Enter${ORNG}]${NEOR} for next test...${RSET}"
	read -p ""
	rm -f "$TEMP_FILE"
done

echo -e "\t  ${PINK}>> ${ORNG}Exited ${BABY}Super-Cool-${MINT}Miso${BABY}-Powered ${ORNG}Tester${PINK} <<${RSET}\n"
exit 0
